# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fall.ui'
#
# Created: Fri Jan 03 21:40:07 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow22(object):
    def setupUi(self, MainWindow22):
        MainWindow22.setObjectName(_fromUtf8("MainWindow22"))
        MainWindow22.resize(842, 570)
        self.centralwidget = QtGui.QWidget(MainWindow22)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 331, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 110, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 250, 731, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(400, 260, 31, 241))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(240, 180, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(300, 180, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(570, 50, 211, 201))
        self.frame.setStyleSheet(_fromUtf8("background-image: url(:/newPrefix/p2.jpg);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 260, 351, 241))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label01 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label01.setFont(font)
        self.label01.setText(_fromUtf8(""))
        self.label01.setObjectName(_fromUtf8("label01"))
        self.verticalLayout.addWidget(self.label01)
        self.label02 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label02.setFont(font)
        self.label02.setText(_fromUtf8(""))
        self.label02.setObjectName(_fromUtf8("label02"))
        self.verticalLayout.addWidget(self.label02)
        self.label03 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label03.setFont(font)
        self.label03.setText(_fromUtf8(""))
        self.label03.setObjectName(_fromUtf8("label03"))
        self.verticalLayout.addWidget(self.label03)
        self.label04 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label04.setFont(font)
        self.label04.setText(_fromUtf8(""))
        self.label04.setObjectName(_fromUtf8("label04"))
        self.verticalLayout.addWidget(self.label04)
        self.label05 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label05.setFont(font)
        self.label05.setText(_fromUtf8(""))
        self.label05.setObjectName(_fromUtf8("label05"))
        self.verticalLayout.addWidget(self.label05)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(420, 260, 351, 241))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label06 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label06.setFont(font)
        self.label06.setText(_fromUtf8(""))
        self.label06.setObjectName(_fromUtf8("label06"))
        self.verticalLayout_2.addWidget(self.label06)
        self.label07 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label07.setFont(font)
        self.label07.setText(_fromUtf8(""))
        self.label07.setObjectName(_fromUtf8("label07"))
        self.verticalLayout_2.addWidget(self.label07)
        self.label08 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label08.setFont(font)
        self.label08.setText(_fromUtf8(""))
        self.label08.setObjectName(_fromUtf8("label08"))
        self.verticalLayout_2.addWidget(self.label08)
        self.label09 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label09.setFont(font)
        self.label09.setText(_fromUtf8(""))
        self.label09.setObjectName(_fromUtf8("label09"))
        self.verticalLayout_2.addWidget(self.label09)
        self.label10 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setText(_fromUtf8(""))
        self.label10.setObjectName(_fromUtf8("label10"))
        self.verticalLayout_2.addWidget(self.label10)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 510, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow22.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow22)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow22.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow22)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow22.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow22)
        QtCore.QMetaObject.connectSlotsByName(MainWindow22)

    def retranslateUi(self, MainWindow22):
        MainWindow22.setWindowTitle(_translate("MainWindow22", "MainWindow", None))
        self.label.setText(_translate("MainWindow22", "FALL OF WICKETS", None))
        self.label_14.setText(_translate("MainWindow22", "Extras -", None))
        self.pushButton.setText(_translate("MainWindow22", "Close", None))

import pro

