# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playing_elev2.ui'
#
# Created: Fri Jan 03 21:28:45 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_elev2(object):
    def setupUi(self, MainWindow_elev2):
        MainWindow_elev2.setObjectName(_fromUtf8("MainWindow_elev2"))
        MainWindow_elev2.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow_elev2)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(71, 31, 75, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 90, 111, 421))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_12 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.verticalLayout_3.addWidget(self.comboBox_12)
        self.line_14 = QtGui.QFrame(self.layoutWidget)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.verticalLayout_3.addWidget(self.line_14)
        self.comboBox_13 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.verticalLayout_3.addWidget(self.comboBox_13)
        self.line_11 = QtGui.QFrame(self.layoutWidget)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_3.addWidget(self.line_11)
        self.comboBox_14 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.verticalLayout_3.addWidget(self.comboBox_14)
        self.line_12 = QtGui.QFrame(self.layoutWidget)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_3.addWidget(self.line_12)
        self.comboBox_15 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_15.setObjectName(_fromUtf8("comboBox_15"))
        self.verticalLayout_3.addWidget(self.comboBox_15)
        self.line_24 = QtGui.QFrame(self.layoutWidget)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.verticalLayout_3.addWidget(self.line_24)
        self.comboBox_16 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_16.setObjectName(_fromUtf8("comboBox_16"))
        self.verticalLayout_3.addWidget(self.comboBox_16)
        self.line_25 = QtGui.QFrame(self.layoutWidget)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.verticalLayout_3.addWidget(self.line_25)
        self.comboBox_17 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_17.setObjectName(_fromUtf8("comboBox_17"))
        self.verticalLayout_3.addWidget(self.comboBox_17)
        self.line_26 = QtGui.QFrame(self.layoutWidget)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.verticalLayout_3.addWidget(self.line_26)
        self.comboBox_18 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_18.setObjectName(_fromUtf8("comboBox_18"))
        self.verticalLayout_3.addWidget(self.comboBox_18)
        self.line_27 = QtGui.QFrame(self.layoutWidget)
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.verticalLayout_3.addWidget(self.line_27)
        self.comboBox_19 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_19.setObjectName(_fromUtf8("comboBox_19"))
        self.verticalLayout_3.addWidget(self.comboBox_19)
        self.line_28 = QtGui.QFrame(self.layoutWidget)
        self.line_28.setFrameShape(QtGui.QFrame.HLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.verticalLayout_3.addWidget(self.line_28)
        self.comboBox_20 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_20.setObjectName(_fromUtf8("comboBox_20"))
        self.verticalLayout_3.addWidget(self.comboBox_20)
        self.line_29 = QtGui.QFrame(self.layoutWidget)
        self.line_29.setFrameShape(QtGui.QFrame.HLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.verticalLayout_3.addWidget(self.line_29)
        self.comboBox_21 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_21.setObjectName(_fromUtf8("comboBox_21"))
        self.verticalLayout_3.addWidget(self.comboBox_21)
        self.line_30 = QtGui.QFrame(self.layoutWidget)
        self.line_30.setFrameShape(QtGui.QFrame.HLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.verticalLayout_3.addWidget(self.line_30)
        self.comboBox_22 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_22.setObjectName(_fromUtf8("comboBox_22"))
        self.verticalLayout_3.addWidget(self.comboBox_22)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(189, 31, 241, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(160, 90, 211, 421))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_2.addWidget(self.comboBox)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.line_2 = QtGui.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.line_3 = QtGui.QFrame(self.layoutWidget_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.verticalLayout_2.addWidget(self.comboBox_4)
        self.line_4 = QtGui.QFrame(self.layoutWidget_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.comboBox_5 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.verticalLayout_2.addWidget(self.comboBox_5)
        self.line_5 = QtGui.QFrame(self.layoutWidget_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_2.addWidget(self.line_5)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.verticalLayout_2.addWidget(self.comboBox_6)
        self.line_6 = QtGui.QFrame(self.layoutWidget_2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_2.addWidget(self.line_6)
        self.comboBox_7 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.verticalLayout_2.addWidget(self.comboBox_7)
        self.line_7 = QtGui.QFrame(self.layoutWidget_2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_2.addWidget(self.line_7)
        self.comboBox_8 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.verticalLayout_2.addWidget(self.comboBox_8)
        self.line_8 = QtGui.QFrame(self.layoutWidget_2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_2.addWidget(self.line_8)
        self.comboBox_9 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.verticalLayout_2.addWidget(self.comboBox_9)
        self.line_9 = QtGui.QFrame(self.layoutWidget_2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_2.addWidget(self.line_9)
        self.comboBox_10 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.verticalLayout_2.addWidget(self.comboBox_10)
        self.line_10 = QtGui.QFrame(self.layoutWidget_2)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_2.addWidget(self.line_10)
        self.comboBox_11 = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.verticalLayout_2.addWidget(self.comboBox_11)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(540, 100, 211, 231))
        self.frame.setStyleSheet(_fromUtf8("background-image: url(:/newPrefix/download.jpg);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 90, 111, 421))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.line_13 = QtGui.QFrame(self.layoutWidget_3)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout.addWidget(self.line_13)
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.line_15 = QtGui.QFrame(self.layoutWidget_3)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.verticalLayout.addWidget(self.line_15)
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.line_16 = QtGui.QFrame(self.layoutWidget_3)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.verticalLayout.addWidget(self.line_16)
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.line_17 = QtGui.QFrame(self.layoutWidget_3)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout.addWidget(self.line_17)
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.line_18 = QtGui.QFrame(self.layoutWidget_3)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.verticalLayout.addWidget(self.line_18)
        self.label_6 = QtGui.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.line_19 = QtGui.QFrame(self.layoutWidget_3)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.verticalLayout.addWidget(self.line_19)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.line_20 = QtGui.QFrame(self.layoutWidget_3)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.verticalLayout.addWidget(self.line_20)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.line_21 = QtGui.QFrame(self.layoutWidget_3)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.verticalLayout.addWidget(self.line_21)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.line_22 = QtGui.QFrame(self.layoutWidget_3)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.verticalLayout.addWidget(self.line_22)
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.line_23 = QtGui.QFrame(self.layoutWidget_3)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.verticalLayout.addWidget(self.line_23)
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 520, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 520, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow_elev2.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_elev2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow_elev2.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_elev2)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_elev2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_elev2)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_12.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_13.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_14.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_15.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_5, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_16.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_6, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_17.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_7, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_18.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_8, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_19.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_9, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_20.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_10, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_21.setCurrentIndex)
        QtCore.QObject.connect(self.comboBox_11, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBox_22.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_elev2)

    def retranslateUi(self, MainWindow_elev2):
        MainWindow_elev2.setWindowTitle(_translate("MainWindow_elev2", "MainWindow", None))
        self.label_12.setText(_translate("MainWindow_elev2", "Team", None))
        self.label.setText(_translate("MainWindow_elev2", "Player 1", None))
        self.label_2.setText(_translate("MainWindow_elev2", "Player 2", None))
        self.label_3.setText(_translate("MainWindow_elev2", "Player 3", None))
        self.label_4.setText(_translate("MainWindow_elev2", "Player 4", None))
        self.label_5.setText(_translate("MainWindow_elev2", "Player 5", None))
        self.label_6.setText(_translate("MainWindow_elev2", "Player 6", None))
        self.label_7.setText(_translate("MainWindow_elev2", "Player 7", None))
        self.label_8.setText(_translate("MainWindow_elev2", "Player 8", None))
        self.label_9.setText(_translate("MainWindow_elev2", "Player 9", None))
        self.label_10.setText(_translate("MainWindow_elev2", "Player 10", None))
        self.label_11.setText(_translate("MainWindow_elev2", "Player 11", None))
        self.pushButton_2.setText(_translate("MainWindow_elev2", "Back", None))
        self.pushButton.setText(_translate("MainWindow_elev2", "Next", None))

import pro

'''if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow_elev2 = QtGui.QMainWindow()
    ui = Ui_MainWindow_elev2()
    ui.setupUi(MainWindow_elev2)
    MainWindow_elev2.show()
    sys.exit(app.exec_())
'''
