# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sl10.ui'
#
# Created: Fri Apr 05 16:42:31 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow10(object):
    def setupUi(self, MainWindow10):
        MainWindow10.setObjectName(_fromUtf8("MainWindow10"))
        MainWindow10.resize(844, 570)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/new/Users/Gurvinder/Desktop/indian-cricket-logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow10.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow10)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 0, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 130, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 140, 711, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 130, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 160, 161, 321))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setText(_fromUtf8(""))
        self.label11.setObjectName(_fromUtf8("label11"))
        self.verticalLayout.addWidget(self.label11)
        self.label21 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label21.setFont(font)
        self.label21.setText(_fromUtf8(""))
        self.label21.setObjectName(_fromUtf8("label21"))
        self.verticalLayout.addWidget(self.label21)
        self.label31 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label31.setFont(font)
        self.label31.setText(_fromUtf8(""))
        self.label31.setObjectName(_fromUtf8("label31"))
        self.verticalLayout.addWidget(self.label31)
        self.label41 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label41.setFont(font)
        self.label41.setText(_fromUtf8(""))
        self.label41.setObjectName(_fromUtf8("label41"))
        self.verticalLayout.addWidget(self.label41)
        self.label51 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label51.setFont(font)
        self.label51.setText(_fromUtf8(""))
        self.label51.setObjectName(_fromUtf8("label51"))
        self.verticalLayout.addWidget(self.label51)
        self.label61 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label61.setFont(font)
        self.label61.setText(_fromUtf8(""))
        self.label61.setObjectName(_fromUtf8("label61"))
        self.verticalLayout.addWidget(self.label61)
        self.label71 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label71.setFont(font)
        self.label71.setText(_fromUtf8(""))
        self.label71.setObjectName(_fromUtf8("label71"))
        self.verticalLayout.addWidget(self.label71)
        self.label81 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label81.setFont(font)
        self.label81.setText(_fromUtf8(""))
        self.label81.setObjectName(_fromUtf8("label81"))
        self.verticalLayout.addWidget(self.label81)
        self.label91 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label91.setFont(font)
        self.label91.setText(_fromUtf8(""))
        self.label91.setObjectName(_fromUtf8("label91"))
        self.verticalLayout.addWidget(self.label91)
        self.label101 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label101.setFont(font)
        self.label101.setText(_fromUtf8(""))
        self.label101.setObjectName(_fromUtf8("label101"))
        self.verticalLayout.addWidget(self.label101)
        self.label111 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label111.setFont(font)
        self.label111.setText(_fromUtf8(""))
        self.label111.setObjectName(_fromUtf8("label111"))
        self.verticalLayout.addWidget(self.label111)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 160, 361, 321))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label12 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setText(_fromUtf8(""))
        self.label12.setObjectName(_fromUtf8("label12"))
        self.verticalLayout_2.addWidget(self.label12)
        self.label22 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label22.setFont(font)
        self.label22.setText(_fromUtf8(""))
        self.label22.setObjectName(_fromUtf8("label22"))
        self.verticalLayout_2.addWidget(self.label22)
        self.label32 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label32.setFont(font)
        self.label32.setText(_fromUtf8(""))
        self.label32.setObjectName(_fromUtf8("label32"))
        self.verticalLayout_2.addWidget(self.label32)
        self.label42 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label42.setFont(font)
        self.label42.setText(_fromUtf8(""))
        self.label42.setObjectName(_fromUtf8("label42"))
        self.verticalLayout_2.addWidget(self.label42)
        self.label52 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label52.setFont(font)
        self.label52.setText(_fromUtf8(""))
        self.label52.setObjectName(_fromUtf8("label52"))
        self.verticalLayout_2.addWidget(self.label52)
        self.label62 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label62.setFont(font)
        self.label62.setText(_fromUtf8(""))
        self.label62.setObjectName(_fromUtf8("label62"))
        self.verticalLayout_2.addWidget(self.label62)
        self.label72 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label72.setFont(font)
        self.label72.setText(_fromUtf8(""))
        self.label72.setObjectName(_fromUtf8("label72"))
        self.verticalLayout_2.addWidget(self.label72)
        self.label82 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label82.setFont(font)
        self.label82.setText(_fromUtf8(""))
        self.label82.setObjectName(_fromUtf8("label82"))
        self.verticalLayout_2.addWidget(self.label82)
        self.label92 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label92.setFont(font)
        self.label92.setText(_fromUtf8(""))
        self.label92.setObjectName(_fromUtf8("label92"))
        self.verticalLayout_2.addWidget(self.label92)
        self.label102 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label102.setFont(font)
        self.label102.setText(_fromUtf8(""))
        self.label102.setObjectName(_fromUtf8("label102"))
        self.verticalLayout_2.addWidget(self.label102)
        self.label112 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label112.setFont(font)
        self.label112.setText(_fromUtf8(""))
        self.label112.setObjectName(_fromUtf8("label112"))
        self.verticalLayout_2.addWidget(self.label112)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 500, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow10.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow10)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow10.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow10)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow10.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow10)

    def retranslateUi(self, MainWindow10):
        MainWindow10.setWindowTitle(_translate("MainWindow10", "CRICKET  APP", None))
        self.label.setText(_translate("MainWindow10", "BOWLING STATS", None))
        self.label_3.setText(_translate("MainWindow10", "Bowler Name", None))
        self.label_4.setText(_translate("MainWindow10", "Over - Run - Wicket - Economy - Maiden - Wide - Noball", None))
        self.pushButton.setText(_translate("MainWindow10", "Close", None))


