# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sl11.1.2.ui'
#
# Created: Fri Jan 03 20:00:43 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow123(object):
    def setupUi(self, MainWindow123):
        MainWindow123.setObjectName(_fromUtf8("MainWindow123"))
        MainWindow123.resize(820, 673)
        self.centralwidget = QtGui.QWidget(MainWindow123)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(490, 480, 241, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(205, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 60, 181, 512))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit01 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit01.setObjectName(_fromUtf8("lineEdit01"))
        self.verticalLayout.addWidget(self.lineEdit01)
        self.line_39 = QtGui.QFrame(self.layoutWidget_2)
        self.line_39.setFrameShape(QtGui.QFrame.HLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.verticalLayout.addWidget(self.line_39)
        self.lineEdit02 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit02.setObjectName(_fromUtf8("lineEdit02"))
        self.verticalLayout.addWidget(self.lineEdit02)
        self.line_37 = QtGui.QFrame(self.layoutWidget_2)
        self.line_37.setFrameShape(QtGui.QFrame.HLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.verticalLayout.addWidget(self.line_37)
        self.lineEdit03 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit03.setObjectName(_fromUtf8("lineEdit03"))
        self.verticalLayout.addWidget(self.lineEdit03)
        self.line_34 = QtGui.QFrame(self.layoutWidget_2)
        self.line_34.setFrameShape(QtGui.QFrame.HLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.verticalLayout.addWidget(self.line_34)
        self.lineEdit04 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit04.setObjectName(_fromUtf8("lineEdit04"))
        self.verticalLayout.addWidget(self.lineEdit04)
        self.line_33 = QtGui.QFrame(self.layoutWidget_2)
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.verticalLayout.addWidget(self.line_33)
        self.lineEdit05 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit05.setObjectName(_fromUtf8("lineEdit05"))
        self.verticalLayout.addWidget(self.lineEdit05)
        self.line_32 = QtGui.QFrame(self.layoutWidget_2)
        self.line_32.setFrameShape(QtGui.QFrame.HLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.verticalLayout.addWidget(self.line_32)
        self.lineEdit06 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit06.setObjectName(_fromUtf8("lineEdit06"))
        self.verticalLayout.addWidget(self.lineEdit06)
        self.line_31 = QtGui.QFrame(self.layoutWidget_2)
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.verticalLayout.addWidget(self.line_31)
        self.lineEdit07 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit07.setObjectName(_fromUtf8("lineEdit07"))
        self.verticalLayout.addWidget(self.lineEdit07)
        self.line_36 = QtGui.QFrame(self.layoutWidget_2)
        self.line_36.setFrameShape(QtGui.QFrame.HLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.verticalLayout.addWidget(self.line_36)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout.addWidget(self.lineEdit_9)
        self.line_38 = QtGui.QFrame(self.layoutWidget_2)
        self.line_38.setFrameShape(QtGui.QFrame.HLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.verticalLayout.addWidget(self.line_38)
        self.lineEdit09 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit09.setObjectName(_fromUtf8("lineEdit09"))
        self.verticalLayout.addWidget(self.lineEdit09)
        self.line_27 = QtGui.QFrame(self.layoutWidget_2)
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.verticalLayout.addWidget(self.line_27)
        self.lineEdit10 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.verticalLayout.addWidget(self.lineEdit10)
        self.line_28 = QtGui.QFrame(self.layoutWidget_2)
        self.line_28.setFrameShape(QtGui.QFrame.HLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.verticalLayout.addWidget(self.line_28)
        self.lineEdit11 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.verticalLayout.addWidget(self.lineEdit11)
        self.line_29 = QtGui.QFrame(self.layoutWidget_2)
        self.line_29.setFrameShape(QtGui.QFrame.HLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.verticalLayout.addWidget(self.line_29)
        self.lineEdit11_5 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_5.setObjectName(_fromUtf8("lineEdit11_5"))
        self.verticalLayout.addWidget(self.lineEdit11_5)
        self.line_30 = QtGui.QFrame(self.layoutWidget_2)
        self.line_30.setFrameShape(QtGui.QFrame.HLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.verticalLayout.addWidget(self.line_30)
        self.lineEdit11_4 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_4.setObjectName(_fromUtf8("lineEdit11_4"))
        self.verticalLayout.addWidget(self.lineEdit11_4)
        self.line_14 = QtGui.QFrame(self.layoutWidget_2)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.verticalLayout.addWidget(self.line_14)
        self.lineEdit11_3 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_3.setObjectName(_fromUtf8("lineEdit11_3"))
        self.verticalLayout.addWidget(self.lineEdit11_3)
        self.line_15 = QtGui.QFrame(self.layoutWidget_2)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.verticalLayout.addWidget(self.line_15)
        self.lineEdit11_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_2.setObjectName(_fromUtf8("lineEdit11_2"))
        self.verticalLayout.addWidget(self.lineEdit11_2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(460, 50, 311, 381))
        self.frame.setStyleSheet(_fromUtf8("background-image: url(:/newPrefix/144048.2.jpg);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 60, 101, 511))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.line_3 = QtGui.QFrame(self.layoutWidget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_42 = QtGui.QFrame(self.layoutWidget_3)
        self.line_42.setFrameShape(QtGui.QFrame.HLine)
        self.line_42.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_42.setObjectName(_fromUtf8("line_42"))
        self.verticalLayout_2.addWidget(self.line_42)
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.line_41 = QtGui.QFrame(self.layoutWidget_3)
        self.line_41.setFrameShape(QtGui.QFrame.HLine)
        self.line_41.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_41.setObjectName(_fromUtf8("line_41"))
        self.verticalLayout_2.addWidget(self.line_41)
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_40 = QtGui.QFrame(self.layoutWidget_3)
        self.line_40.setFrameShape(QtGui.QFrame.HLine)
        self.line_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_40.setObjectName(_fromUtf8("line_40"))
        self.verticalLayout_2.addWidget(self.line_40)
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.line_35 = QtGui.QFrame(self.layoutWidget_3)
        self.line_35.setFrameShape(QtGui.QFrame.HLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.verticalLayout_2.addWidget(self.line_35)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.line_21 = QtGui.QFrame(self.layoutWidget_3)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.verticalLayout_2.addWidget(self.line_21)
        self.label_6 = QtGui.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.line_8 = QtGui.QFrame(self.layoutWidget_3)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_2.addWidget(self.line_8)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.line_19 = QtGui.QFrame(self.layoutWidget_3)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.verticalLayout_2.addWidget(self.line_19)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.line_20 = QtGui.QFrame(self.layoutWidget_3)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.verticalLayout_2.addWidget(self.line_20)
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.line_26 = QtGui.QFrame(self.layoutWidget_3)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.verticalLayout_2.addWidget(self.line_26)
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.line_25 = QtGui.QFrame(self.layoutWidget_3)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.verticalLayout_2.addWidget(self.line_25)
        self.label_14 = QtGui.QLabel(self.layoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.line_22 = QtGui.QFrame(self.layoutWidget_3)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.verticalLayout_2.addWidget(self.line_22)
        self.label_17 = QtGui.QLabel(self.layoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_2.addWidget(self.label_17)
        self.line_23 = QtGui.QFrame(self.layoutWidget_3)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.verticalLayout_2.addWidget(self.line_23)
        self.label_15 = QtGui.QLabel(self.layoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_2.addWidget(self.label_15)
        self.line_24 = QtGui.QFrame(self.layoutWidget_3)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.verticalLayout_2.addWidget(self.line_24)
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.layoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(350, 60, 80, 512))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox)
        self.line_2 = QtGui.QFrame(self.layoutWidget_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.line_4 = QtGui.QFrame(self.layoutWidget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_3)
        self.line_5 = QtGui.QFrame(self.layoutWidget_4)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_4)
        self.line_13 = QtGui.QFrame(self.layoutWidget_4)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_3.addWidget(self.line_13)
        self.comboBox_5 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_5)
        self.line_6 = QtGui.QFrame(self.layoutWidget_4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_3.addWidget(self.line_6)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_6)
        self.line_12 = QtGui.QFrame(self.layoutWidget_4)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_3.addWidget(self.line_12)
        self.comboBox_7 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_7)
        self.line_16 = QtGui.QFrame(self.layoutWidget_4)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.verticalLayout_3.addWidget(self.line_16)
        self.comboBox_8 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_8)
        self.line_17 = QtGui.QFrame(self.layoutWidget_4)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout_3.addWidget(self.line_17)
        self.comboBox_9 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_9)
        self.line_18 = QtGui.QFrame(self.layoutWidget_4)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.verticalLayout_3.addWidget(self.line_18)
        self.comboBox_10 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_10)
        self.line_9 = QtGui.QFrame(self.layoutWidget_4)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_3.addWidget(self.line_9)
        self.comboBox_11 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_11)
        self.line_10 = QtGui.QFrame(self.layoutWidget_4)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_3.addWidget(self.line_10)
        self.comboBox_13 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_13)
        self.line_11 = QtGui.QFrame(self.layoutWidget_4)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_3.addWidget(self.line_11)
        self.comboBox_14 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_14)
        self.line = QtGui.QFrame(self.layoutWidget_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.comboBox_15 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_15.setObjectName(_fromUtf8("comboBox_15"))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_15)
        self.line_7 = QtGui.QFrame(self.layoutWidget_4)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_3.addWidget(self.line_7)
        self.comboBox_16 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_16.setObjectName(_fromUtf8("comboBox_16"))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_16)
        self.comboBox_12 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_12.setEnabled(False)
        self.comboBox_12.setGeometry(QtCore.QRect(130, 610, 211, 22))
        self.comboBox_12.setDuplicatesEnabled(False)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 610, 171, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 590, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(130, 580, 241, 17))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        MainWindow123.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow123)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow123.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow123)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow123.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow123)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_12.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow123)

    def retranslateUi(self, MainWindow123):
        MainWindow123.setWindowTitle(_translate("MainWindow123", "CRICKET APP", None))
        self.pushButton.setText(_translate("MainWindow123", "NEXT", None))
        self.pushButton_2.setText(_translate("MainWindow123", "Back", None))
        self.label_12.setText(_translate("MainWindow123", "TEAM", None))
        self.label.setText(_translate("MainWindow123", "Player 1", None))
        self.label_2.setText(_translate("MainWindow123", "Player 2", None))
        self.label_3.setText(_translate("MainWindow123", "Player 3", None))
        self.label_4.setText(_translate("MainWindow123", "Player 4", None))
        self.label_5.setText(_translate("MainWindow123", "Player 5", None))
        self.label_7.setText(_translate("MainWindow123", "Player 6", None))
        self.label_6.setText(_translate("MainWindow123", "Player 7", None))
        self.label_8.setText(_translate("MainWindow123", "Player 8", None))
        self.label_9.setText(_translate("MainWindow123", "Player 9", None))
        self.label_10.setText(_translate("MainWindow123", "Player 10", None))
        self.label_11.setText(_translate("MainWindow123", "Player 11", None))
        self.label_14.setText(_translate("MainWindow123", "Player 12", None))
        self.label_17.setText(_translate("MainWindow123", "Player 13", None))
        self.label_15.setText(_translate("MainWindow123", "Player 14", None))
        self.label_16.setText(_translate("MainWindow123", "Player 15", None))
        self.comboBox.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_8.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_9.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_10.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_11.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_13.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_13.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_13.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_14.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_14.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_14.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_15.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_15.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_15.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.comboBox_16.setItemText(0, _translate("MainWindow123", "Batsman", None))
        self.comboBox_16.setItemText(1, _translate("MainWindow123", "Bowler", None))
        self.comboBox_16.setItemText(2, _translate("MainWindow123", "All rounder", None))
        self.pushButton_5.setText(_translate("MainWindow123", "IMPORT EXHISTING", None))
        self.pushButton_3.setText(_translate("MainWindow123", "ADD NEW", None))
        self.checkBox.setText(_translate("MainWindow123", "CLICK HERE TO VIEW EXHISTING TEAMS", None))

import pro

'''

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow123 = QtGui.QMainWindow()
    ui = Ui_MainWindow123()
    ui.setupUi(MainWindow123)
    MainWindow123.show()
    sys.exit(app.exec_())'''

