# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sl3.1.2.ui'
#
# Created: Fri Jan 03 16:01:45 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog001(object):
    def setupUi(self, Dialog001):
        Dialog001.setObjectName(_fromUtf8("Dialog001"))
        Dialog001.resize(889, 663)
        self.label_12 = QtGui.QLabel(Dialog001)
        self.label_12.setGeometry(QtCore.QRect(80, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog001)
        self.label_13.setGeometry(QtCore.QRect(200, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.frame = QtGui.QFrame(Dialog001)
        self.frame.setGeometry(QtCore.QRect(470, 60, 311, 381))
        self.frame.setStyleSheet(_fromUtf8("\n"
"background-image: url(:/newPrefix/144048.2.jpg);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(Dialog001)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 490, 241, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtGui.QPushButton(Dialog001)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 620, 191, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.comboBox_12 = QtGui.QComboBox(Dialog001)
        self.comboBox_12.setEnabled(False)
        self.comboBox_12.setGeometry(QtCore.QRect(209, 619, 211, 22))
        self.comboBox_12.setDuplicatesEnabled(False)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.checkBox = QtGui.QCheckBox(Dialog001)
        self.checkBox.setGeometry(QtCore.QRect(209, 589, 241, 17))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton_3 = QtGui.QPushButton(Dialog001)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 600, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.layoutWidget_4 = QtGui.QWidget(Dialog001)
        self.layoutWidget_4.setGeometry(QtCore.QRect(360, 70, 80, 512))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox)
        self.line_2 = QtGui.QFrame(self.layoutWidget_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.line_4 = QtGui.QFrame(self.layoutWidget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_3)
        self.line_5 = QtGui.QFrame(self.layoutWidget_4)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.comboBox_4 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_4)
        self.line_54 = QtGui.QFrame(self.layoutWidget_4)
        self.line_54.setFrameShape(QtGui.QFrame.HLine)
        self.line_54.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_54.setObjectName(_fromUtf8("line_54"))
        self.verticalLayout_3.addWidget(self.line_54)
        self.comboBox_5 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_5)
        self.line_6 = QtGui.QFrame(self.layoutWidget_4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_3.addWidget(self.line_6)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_6)
        self.line_55 = QtGui.QFrame(self.layoutWidget_4)
        self.line_55.setFrameShape(QtGui.QFrame.HLine)
        self.line_55.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_55.setObjectName(_fromUtf8("line_55"))
        self.verticalLayout_3.addWidget(self.line_55)
        self.comboBox_7 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_7)
        self.line_56 = QtGui.QFrame(self.layoutWidget_4)
        self.line_56.setFrameShape(QtGui.QFrame.HLine)
        self.line_56.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_56.setObjectName(_fromUtf8("line_56"))
        self.verticalLayout_3.addWidget(self.line_56)
        self.comboBox_8 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_8)
        self.line_57 = QtGui.QFrame(self.layoutWidget_4)
        self.line_57.setFrameShape(QtGui.QFrame.HLine)
        self.line_57.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_57.setObjectName(_fromUtf8("line_57"))
        self.verticalLayout_3.addWidget(self.line_57)
        self.comboBox_9 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_9)
        self.line_58 = QtGui.QFrame(self.layoutWidget_4)
        self.line_58.setFrameShape(QtGui.QFrame.HLine)
        self.line_58.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_58.setObjectName(_fromUtf8("line_58"))
        self.verticalLayout_3.addWidget(self.line_58)
        self.comboBox_10 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_10)
        self.line_9 = QtGui.QFrame(self.layoutWidget_4)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_3.addWidget(self.line_9)
        self.comboBox_11 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_11)
        self.line_10 = QtGui.QFrame(self.layoutWidget_4)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_3.addWidget(self.line_10)
        self.comboBox_28 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_28.setObjectName(_fromUtf8("comboBox_28"))
        self.comboBox_28.addItem(_fromUtf8(""))
        self.comboBox_28.addItem(_fromUtf8(""))
        self.comboBox_28.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_28)
        self.line_11 = QtGui.QFrame(self.layoutWidget_4)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_3.addWidget(self.line_11)
        self.comboBox_29 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_29.setObjectName(_fromUtf8("comboBox_29"))
        self.comboBox_29.addItem(_fromUtf8(""))
        self.comboBox_29.addItem(_fromUtf8(""))
        self.comboBox_29.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_29)
        self.line = QtGui.QFrame(self.layoutWidget_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.comboBox_30 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_30.setObjectName(_fromUtf8("comboBox_30"))
        self.comboBox_30.addItem(_fromUtf8(""))
        self.comboBox_30.addItem(_fromUtf8(""))
        self.comboBox_30.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_30)
        self.line_7 = QtGui.QFrame(self.layoutWidget_4)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_3.addWidget(self.line_7)
        self.comboBox_31 = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBox_31.setObjectName(_fromUtf8("comboBox_31"))
        self.comboBox_31.addItem(_fromUtf8(""))
        self.comboBox_31.addItem(_fromUtf8(""))
        self.comboBox_31.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_31)
        self.label_14 = QtGui.QLabel(Dialog001)
        self.label_14.setGeometry(QtCore.QRect(215, -40, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.layoutWidget_3 = QtGui.QWidget(Dialog001)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 70, 101, 511))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.line_3 = QtGui.QFrame(self.layoutWidget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_73 = QtGui.QFrame(self.layoutWidget_3)
        self.line_73.setFrameShape(QtGui.QFrame.HLine)
        self.line_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_73.setObjectName(_fromUtf8("line_73"))
        self.verticalLayout_2.addWidget(self.line_73)
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.line_74 = QtGui.QFrame(self.layoutWidget_3)
        self.line_74.setFrameShape(QtGui.QFrame.HLine)
        self.line_74.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_74.setObjectName(_fromUtf8("line_74"))
        self.verticalLayout_2.addWidget(self.line_74)
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_75 = QtGui.QFrame(self.layoutWidget_3)
        self.line_75.setFrameShape(QtGui.QFrame.HLine)
        self.line_75.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_75.setObjectName(_fromUtf8("line_75"))
        self.verticalLayout_2.addWidget(self.line_75)
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.line_76 = QtGui.QFrame(self.layoutWidget_3)
        self.line_76.setFrameShape(QtGui.QFrame.HLine)
        self.line_76.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_76.setObjectName(_fromUtf8("line_76"))
        self.verticalLayout_2.addWidget(self.line_76)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.line_77 = QtGui.QFrame(self.layoutWidget_3)
        self.line_77.setFrameShape(QtGui.QFrame.HLine)
        self.line_77.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_77.setObjectName(_fromUtf8("line_77"))
        self.verticalLayout_2.addWidget(self.line_77)
        self.label_6 = QtGui.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.line_8 = QtGui.QFrame(self.layoutWidget_3)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_2.addWidget(self.line_8)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.line_78 = QtGui.QFrame(self.layoutWidget_3)
        self.line_78.setFrameShape(QtGui.QFrame.HLine)
        self.line_78.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_78.setObjectName(_fromUtf8("line_78"))
        self.verticalLayout_2.addWidget(self.line_78)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.line_79 = QtGui.QFrame(self.layoutWidget_3)
        self.line_79.setFrameShape(QtGui.QFrame.HLine)
        self.line_79.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_79.setObjectName(_fromUtf8("line_79"))
        self.verticalLayout_2.addWidget(self.line_79)
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.line_80 = QtGui.QFrame(self.layoutWidget_3)
        self.line_80.setFrameShape(QtGui.QFrame.HLine)
        self.line_80.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_80.setObjectName(_fromUtf8("line_80"))
        self.verticalLayout_2.addWidget(self.line_80)
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.line_81 = QtGui.QFrame(self.layoutWidget_3)
        self.line_81.setFrameShape(QtGui.QFrame.HLine)
        self.line_81.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_81.setObjectName(_fromUtf8("line_81"))
        self.verticalLayout_2.addWidget(self.line_81)
        self.label_30 = QtGui.QLabel(self.layoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_2.addWidget(self.label_30)
        self.line_82 = QtGui.QFrame(self.layoutWidget_3)
        self.line_82.setFrameShape(QtGui.QFrame.HLine)
        self.line_82.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_82.setObjectName(_fromUtf8("line_82"))
        self.verticalLayout_2.addWidget(self.line_82)
        self.label_31 = QtGui.QLabel(self.layoutWidget_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_2.addWidget(self.label_31)
        self.line_83 = QtGui.QFrame(self.layoutWidget_3)
        self.line_83.setFrameShape(QtGui.QFrame.HLine)
        self.line_83.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_83.setObjectName(_fromUtf8("line_83"))
        self.verticalLayout_2.addWidget(self.line_83)
        self.label_32 = QtGui.QLabel(self.layoutWidget_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_2.addWidget(self.label_32)
        self.line_84 = QtGui.QFrame(self.layoutWidget_3)
        self.line_84.setFrameShape(QtGui.QFrame.HLine)
        self.line_84.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_84.setObjectName(_fromUtf8("line_84"))
        self.verticalLayout_2.addWidget(self.line_84)
        self.label_33 = QtGui.QLabel(self.layoutWidget_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(Dialog001)
        self.label_34.setGeometry(QtCore.QRect(90, -40, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.layoutWidget_2 = QtGui.QWidget(Dialog001)
        self.layoutWidget_2.setGeometry(QtCore.QRect(150, 70, 191, 512))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit01 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit01.setObjectName(_fromUtf8("lineEdit01"))
        self.verticalLayout.addWidget(self.lineEdit01)
        self.line_59 = QtGui.QFrame(self.layoutWidget_2)
        self.line_59.setFrameShape(QtGui.QFrame.HLine)
        self.line_59.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_59.setObjectName(_fromUtf8("line_59"))
        self.verticalLayout.addWidget(self.line_59)
        self.lineEdit02 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit02.setObjectName(_fromUtf8("lineEdit02"))
        self.verticalLayout.addWidget(self.lineEdit02)
        self.line_60 = QtGui.QFrame(self.layoutWidget_2)
        self.line_60.setFrameShape(QtGui.QFrame.HLine)
        self.line_60.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_60.setObjectName(_fromUtf8("line_60"))
        self.verticalLayout.addWidget(self.line_60)
        self.lineEdit03 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit03.setObjectName(_fromUtf8("lineEdit03"))
        self.verticalLayout.addWidget(self.lineEdit03)
        self.line_61 = QtGui.QFrame(self.layoutWidget_2)
        self.line_61.setFrameShape(QtGui.QFrame.HLine)
        self.line_61.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_61.setObjectName(_fromUtf8("line_61"))
        self.verticalLayout.addWidget(self.line_61)
        self.lineEdit04 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit04.setObjectName(_fromUtf8("lineEdit04"))
        self.verticalLayout.addWidget(self.lineEdit04)
        self.line_62 = QtGui.QFrame(self.layoutWidget_2)
        self.line_62.setFrameShape(QtGui.QFrame.HLine)
        self.line_62.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_62.setObjectName(_fromUtf8("line_62"))
        self.verticalLayout.addWidget(self.line_62)
        self.lineEdit05 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit05.setObjectName(_fromUtf8("lineEdit05"))
        self.verticalLayout.addWidget(self.lineEdit05)
        self.line_63 = QtGui.QFrame(self.layoutWidget_2)
        self.line_63.setFrameShape(QtGui.QFrame.HLine)
        self.line_63.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_63.setObjectName(_fromUtf8("line_63"))
        self.verticalLayout.addWidget(self.line_63)
        self.lineEdit06 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit06.setObjectName(_fromUtf8("lineEdit06"))
        self.verticalLayout.addWidget(self.lineEdit06)
        self.line_64 = QtGui.QFrame(self.layoutWidget_2)
        self.line_64.setFrameShape(QtGui.QFrame.HLine)
        self.line_64.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_64.setObjectName(_fromUtf8("line_64"))
        self.verticalLayout.addWidget(self.line_64)
        self.lineEdit07 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit07.setObjectName(_fromUtf8("lineEdit07"))
        self.verticalLayout.addWidget(self.lineEdit07)
        self.line_65 = QtGui.QFrame(self.layoutWidget_2)
        self.line_65.setFrameShape(QtGui.QFrame.HLine)
        self.line_65.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_65.setObjectName(_fromUtf8("line_65"))
        self.verticalLayout.addWidget(self.line_65)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout.addWidget(self.lineEdit_9)
        self.line_66 = QtGui.QFrame(self.layoutWidget_2)
        self.line_66.setFrameShape(QtGui.QFrame.HLine)
        self.line_66.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_66.setObjectName(_fromUtf8("line_66"))
        self.verticalLayout.addWidget(self.line_66)
        self.lineEdit09 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit09.setObjectName(_fromUtf8("lineEdit09"))
        self.verticalLayout.addWidget(self.lineEdit09)
        self.line_67 = QtGui.QFrame(self.layoutWidget_2)
        self.line_67.setFrameShape(QtGui.QFrame.HLine)
        self.line_67.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_67.setObjectName(_fromUtf8("line_67"))
        self.verticalLayout.addWidget(self.line_67)
        self.lineEdit10 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.verticalLayout.addWidget(self.lineEdit10)
        self.line_68 = QtGui.QFrame(self.layoutWidget_2)
        self.line_68.setFrameShape(QtGui.QFrame.HLine)
        self.line_68.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_68.setObjectName(_fromUtf8("line_68"))
        self.verticalLayout.addWidget(self.line_68)
        self.lineEdit11 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.verticalLayout.addWidget(self.lineEdit11)
        self.line_69 = QtGui.QFrame(self.layoutWidget_2)
        self.line_69.setFrameShape(QtGui.QFrame.HLine)
        self.line_69.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_69.setObjectName(_fromUtf8("line_69"))
        self.verticalLayout.addWidget(self.line_69)
        self.lineEdit11_7 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_7.setObjectName(_fromUtf8("lineEdit11_7"))
        self.verticalLayout.addWidget(self.lineEdit11_7)
        self.line_70 = QtGui.QFrame(self.layoutWidget_2)
        self.line_70.setFrameShape(QtGui.QFrame.HLine)
        self.line_70.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_70.setObjectName(_fromUtf8("line_70"))
        self.verticalLayout.addWidget(self.line_70)
        self.lineEdit11_8 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_8.setObjectName(_fromUtf8("lineEdit11_8"))
        self.verticalLayout.addWidget(self.lineEdit11_8)
        self.line_71 = QtGui.QFrame(self.layoutWidget_2)
        self.line_71.setFrameShape(QtGui.QFrame.HLine)
        self.line_71.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_71.setObjectName(_fromUtf8("line_71"))
        self.verticalLayout.addWidget(self.line_71)
        self.lineEdit11_9 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_9.setObjectName(_fromUtf8("lineEdit11_9"))
        self.verticalLayout.addWidget(self.lineEdit11_9)
        self.line_72 = QtGui.QFrame(self.layoutWidget_2)
        self.line_72.setFrameShape(QtGui.QFrame.HLine)
        self.line_72.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_72.setObjectName(_fromUtf8("line_72"))
        self.verticalLayout.addWidget(self.line_72)
        self.lineEdit11_10 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit11_10.setObjectName(_fromUtf8("lineEdit11_10"))
        self.verticalLayout.addWidget(self.lineEdit11_10)

        self.retranslateUi(Dialog001)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_12.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog001)

    def retranslateUi(self, Dialog001):
        Dialog001.setWindowTitle(_translate("Dialog001", "CRICKET APP", None))
        self.label_12.setText(_translate("Dialog001", "TEAM", None))
        self.pushButton.setText(_translate("Dialog001", "NEXT", None))
        self.pushButton_2.setText(_translate("Dialog001", "Back", None))
        self.pushButton_5.setText(_translate("Dialog001", "IMPORT EXHISTING", None))
        self.checkBox.setText(_translate("Dialog001", "CLICK HERE TO VIEW EXHISTING TEAMS", None))
        self.pushButton_3.setText(_translate("Dialog001", "ADD NEW", None))
        self.comboBox.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_2.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_2.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_2.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_3.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_3.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_3.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_4.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_4.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_4.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_5.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_5.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_5.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_6.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_6.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_6.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_7.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_7.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_7.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_8.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_8.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_8.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_9.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_9.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_9.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_10.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_10.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_10.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_11.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_11.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_11.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_28.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_28.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_28.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_29.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_29.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_29.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_30.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_30.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_30.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.comboBox_31.setItemText(0, _translate("Dialog001", "Batsman", None))
        self.comboBox_31.setItemText(1, _translate("Dialog001", "Bowler", None))
        self.comboBox_31.setItemText(2, _translate("Dialog001", "All rounder", None))
        self.label.setText(_translate("Dialog001", "Player 1", None))
        self.label_2.setText(_translate("Dialog001", "Player 2", None))
        self.label_3.setText(_translate("Dialog001", "Player 3", None))
        self.label_4.setText(_translate("Dialog001", "Player 4", None))
        self.label_5.setText(_translate("Dialog001", "Player 5", None))
        self.label_7.setText(_translate("Dialog001", "Player 6", None))
        self.label_6.setText(_translate("Dialog001", "Player 7", None))
        self.label_8.setText(_translate("Dialog001", "Player 8", None))
        self.label_9.setText(_translate("Dialog001", "Player 9", None))
        self.label_10.setText(_translate("Dialog001", "Player 10", None))
        self.label_11.setText(_translate("Dialog001", "Player 11", None))
        self.label_30.setText(_translate("Dialog001", "Player 12", None))
        self.label_31.setText(_translate("Dialog001", "Player 13", None))
        self.label_32.setText(_translate("Dialog001", "Player 14", None))
        self.label_33.setText(_translate("Dialog001", "Player 15", None))
        self.label_34.setText(_translate("Dialog001", "TEAM", None))

import pro

'''
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog001 = QtGui.QDialog()
    ui = Ui_Dialog001()
    ui.setupUi(Dialog001)
    Dialog001.show()
    sys.exit(app.exec_())'''

