# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sl4.1.2.ui'
#
# Created: Fri Jan 03 22:08:07 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow05(object):
    def setupUi(self, MainWindow05):
        MainWindow05.setObjectName(_fromUtf8("MainWindow05"))
        MainWindow05.resize(873, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/new/Users/Gurvinder/Desktop/indian-cricket-logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow05.setWindowIcon(icon)
        MainWindow05.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow05)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 55, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 0, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 130, 691, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(50, 170, 691, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(50, 210, 691, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(50, 250, 691, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(50, 280, 691, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(50, 320, 691, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(50, 350, 691, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(47, 390, 691, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(47, 420, 691, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(47, 460, 691, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 20, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 530, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 530, 46, 13))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 530, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 110, 191, 391))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label01 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label01.setFont(font)
        self.label01.setStyleSheet(_fromUtf8("background-color: rgb(8, 8, 8);\n"
"color: rgb(255, 255, 255);"))
        self.label01.setText(_fromUtf8(""))
        self.label01.setObjectName(_fromUtf8("label01"))
        self.verticalLayout.addWidget(self.label01)
        self.label02 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label02.setFont(font)
        self.label02.setStyleSheet(_fromUtf8("background-color: rgb(250, 250, 250);"))
        self.label02.setText(_fromUtf8(""))
        self.label02.setObjectName(_fromUtf8("label02"))
        self.verticalLayout.addWidget(self.label02)
        self.label03 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label03.setFont(font)
        self.label03.setStyleSheet(_fromUtf8("background-color: rgb(4, 4, 4);\n"
"color: rgb(255, 255, 255);"))
        self.label03.setText(_fromUtf8(""))
        self.label03.setObjectName(_fromUtf8("label03"))
        self.verticalLayout.addWidget(self.label03)
        self.label04 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label04.setFont(font)
        self.label04.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label04.setText(_fromUtf8(""))
        self.label04.setObjectName(_fromUtf8("label04"))
        self.verticalLayout.addWidget(self.label04)
        self.label05 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label05.setFont(font)
        self.label05.setStyleSheet(_fromUtf8("background-color: rgb(6, 6, 6);\n"
"color: rgb(255, 255, 255);"))
        self.label05.setText(_fromUtf8(""))
        self.label05.setObjectName(_fromUtf8("label05"))
        self.verticalLayout.addWidget(self.label05)
        self.label06 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label06.setFont(font)
        self.label06.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label06.setText(_fromUtf8(""))
        self.label06.setObjectName(_fromUtf8("label06"))
        self.verticalLayout.addWidget(self.label06)
        self.label07 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label07.setFont(font)
        self.label07.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label07.setText(_fromUtf8(""))
        self.label07.setObjectName(_fromUtf8("label07"))
        self.verticalLayout.addWidget(self.label07)
        self.label08 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label08.setFont(font)
        self.label08.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label08.setText(_fromUtf8(""))
        self.label08.setObjectName(_fromUtf8("label08"))
        self.verticalLayout.addWidget(self.label08)
        self.label09 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label09.setFont(font)
        self.label09.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label09.setText(_fromUtf8(""))
        self.label09.setObjectName(_fromUtf8("label09"))
        self.verticalLayout.addWidget(self.label09)
        self.label010 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label010.setFont(font)
        self.label010.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label010.setText(_fromUtf8(""))
        self.label010.setObjectName(_fromUtf8("label010"))
        self.verticalLayout.addWidget(self.label010)
        self.label011 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label011.setFont(font)
        self.label011.setStyleSheet(_fromUtf8("background-color: rgb(7, 7, 7);\n"
"color: rgb(255, 255, 255);"))
        self.label011.setText(_fromUtf8(""))
        self.label011.setObjectName(_fromUtf8("label011"))
        self.verticalLayout.addWidget(self.label011)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 110, 261, 391))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label11 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setStyleSheet(_fromUtf8("background-color: rgb(4, 4, 4);\n"
"color: rgb(255, 255, 255);"))
        self.label11.setText(_fromUtf8(""))
        self.label11.setObjectName(_fromUtf8("label11"))
        self.verticalLayout_2.addWidget(self.label11)
        self.label12 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label12.setText(_fromUtf8(""))
        self.label12.setObjectName(_fromUtf8("label12"))
        self.verticalLayout_2.addWidget(self.label12)
        self.label13 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label13.setFont(font)
        self.label13.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label13.setText(_fromUtf8(""))
        self.label13.setObjectName(_fromUtf8("label13"))
        self.verticalLayout_2.addWidget(self.label13)
        self.label14 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label14.setFont(font)
        self.label14.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label14.setText(_fromUtf8(""))
        self.label14.setObjectName(_fromUtf8("label14"))
        self.verticalLayout_2.addWidget(self.label14)
        self.label15 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label15.setFont(font)
        self.label15.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label15.setText(_fromUtf8(""))
        self.label15.setObjectName(_fromUtf8("label15"))
        self.verticalLayout_2.addWidget(self.label15)
        self.label16 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label16.setFont(font)
        self.label16.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label16.setText(_fromUtf8(""))
        self.label16.setObjectName(_fromUtf8("label16"))
        self.verticalLayout_2.addWidget(self.label16)
        self.label17 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label17.setFont(font)
        self.label17.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label17.setText(_fromUtf8(""))
        self.label17.setObjectName(_fromUtf8("label17"))
        self.verticalLayout_2.addWidget(self.label17)
        self.label18 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label18.setFont(font)
        self.label18.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label18.setText(_fromUtf8(""))
        self.label18.setObjectName(_fromUtf8("label18"))
        self.verticalLayout_2.addWidget(self.label18)
        self.label19 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label19.setFont(font)
        self.label19.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label19.setText(_fromUtf8(""))
        self.label19.setObjectName(_fromUtf8("label19"))
        self.verticalLayout_2.addWidget(self.label19)
        self.label110 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label110.setFont(font)
        self.label110.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label110.setText(_fromUtf8(""))
        self.label110.setObjectName(_fromUtf8("label110"))
        self.verticalLayout_2.addWidget(self.label110)
        self.label111 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label111.setFont(font)
        self.label111.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label111.setText(_fromUtf8(""))
        self.label111.setObjectName(_fromUtf8("label111"))
        self.verticalLayout_2.addWidget(self.label111)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(620, 110, 121, 391))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label21 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label21.setFont(font)
        self.label21.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label21.setText(_fromUtf8(""))
        self.label21.setObjectName(_fromUtf8("label21"))
        self.verticalLayout_3.addWidget(self.label21)
        self.label22 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label22.setFont(font)
        self.label22.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label22.setText(_fromUtf8(""))
        self.label22.setObjectName(_fromUtf8("label22"))
        self.verticalLayout_3.addWidget(self.label22)
        self.label23 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label23.setFont(font)
        self.label23.setStyleSheet(_fromUtf8("background-color: rgb(4, 4, 4);\n"
"color: rgb(255, 255, 255);"))
        self.label23.setText(_fromUtf8(""))
        self.label23.setObjectName(_fromUtf8("label23"))
        self.verticalLayout_3.addWidget(self.label23)
        self.label24 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label24.setFont(font)
        self.label24.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label24.setText(_fromUtf8(""))
        self.label24.setObjectName(_fromUtf8("label24"))
        self.verticalLayout_3.addWidget(self.label24)
        self.label25 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label25.setFont(font)
        self.label25.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label25.setText(_fromUtf8(""))
        self.label25.setObjectName(_fromUtf8("label25"))
        self.verticalLayout_3.addWidget(self.label25)
        self.label26 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label26.setFont(font)
        self.label26.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label26.setText(_fromUtf8(""))
        self.label26.setObjectName(_fromUtf8("label26"))
        self.verticalLayout_3.addWidget(self.label26)
        self.label27 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label27.setFont(font)
        self.label27.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label27.setText(_fromUtf8(""))
        self.label27.setObjectName(_fromUtf8("label27"))
        self.verticalLayout_3.addWidget(self.label27)
        self.label28 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label28.setFont(font)
        self.label28.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);"))
        self.label28.setText(_fromUtf8(""))
        self.label28.setObjectName(_fromUtf8("label28"))
        self.verticalLayout_3.addWidget(self.label28)
        self.label29 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label29.setFont(font)
        self.label29.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label29.setText(_fromUtf8(""))
        self.label29.setObjectName(_fromUtf8("label29"))
        self.verticalLayout_3.addWidget(self.label29)
        self.label210 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label210.setFont(font)
        self.label210.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label210.setText(_fromUtf8(""))
        self.label210.setObjectName(_fromUtf8("label210"))
        self.verticalLayout_3.addWidget(self.label210)
        self.label211 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label211.setFont(font)
        self.label211.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.label211.setText(_fromUtf8(""))
        self.label211.setObjectName(_fromUtf8("label211"))
        self.verticalLayout_3.addWidget(self.label211)
        MainWindow05.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow05)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow05.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow05)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow05.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow05)
        QtCore.QMetaObject.connectSlotsByName(MainWindow05)

    def retranslateUi(self, MainWindow05):
        MainWindow05.setWindowTitle(_translate("MainWindow05", "CRICKET APP", None))
        self.label.setText(_translate("MainWindow05", "Team", None))
        self.label_3.setText(_translate("MainWindow05", "Scorecard", None))
        self.label_5.setText(_translate("MainWindow05", "Extras", None))
        self.pushButton.setText(_translate("MainWindow05", "Close", None))

