# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sl6.ui'
#
# Created: Sat Mar 23 19:31:18 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow009(object):
    def setupUi(self, MainWindow009):
        MainWindow009.setObjectName(_fromUtf8("MainWindow009"))
        MainWindow009.resize(878, 598)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/new/Users/Gurvinder/Desktop/indian-cricket-logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow009.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow009)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(80, 120, 681, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label111_2 = QtGui.QLabel(self.centralwidget)
        self.label111_2.setGeometry(QtCore.QRect(80, 430, 179, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label111_2.setFont(font)
        self.label111_2.setText(_fromUtf8(""))
        self.label111_2.setObjectName(_fromUtf8("label111_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(80, 100, 181, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_2.addWidget(self.label_15)
        self.label11_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label11_2.setFont(font)
        self.label11_2.setText(_fromUtf8(""))
        self.label11_2.setObjectName(_fromUtf8("label11_2"))
        self.verticalLayout_2.addWidget(self.label11_2)
        self.label21_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label21_2.setFont(font)
        self.label21_2.setText(_fromUtf8(""))
        self.label21_2.setObjectName(_fromUtf8("label21_2"))
        self.verticalLayout_2.addWidget(self.label21_2)
        self.label31_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label31_2.setFont(font)
        self.label31_2.setText(_fromUtf8(""))
        self.label31_2.setObjectName(_fromUtf8("label31_2"))
        self.verticalLayout_2.addWidget(self.label31_2)
        self.label41_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label41_2.setFont(font)
        self.label41_2.setText(_fromUtf8(""))
        self.label41_2.setObjectName(_fromUtf8("label41_2"))
        self.verticalLayout_2.addWidget(self.label41_2)
        self.label51_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label51_2.setFont(font)
        self.label51_2.setText(_fromUtf8(""))
        self.label51_2.setObjectName(_fromUtf8("label51_2"))
        self.verticalLayout_2.addWidget(self.label51_2)
        self.label61_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label61_2.setFont(font)
        self.label61_2.setText(_fromUtf8(""))
        self.label61_2.setObjectName(_fromUtf8("label61_2"))
        self.verticalLayout_2.addWidget(self.label61_2)
        self.label71_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label71_2.setFont(font)
        self.label71_2.setText(_fromUtf8(""))
        self.label71_2.setObjectName(_fromUtf8("label71_2"))
        self.verticalLayout_2.addWidget(self.label71_2)
        self.label81_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label81_2.setFont(font)
        self.label81_2.setText(_fromUtf8(""))
        self.label81_2.setObjectName(_fromUtf8("label81_2"))
        self.verticalLayout_2.addWidget(self.label81_2)
        self.label91_3 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label91_3.setFont(font)
        self.label91_3.setText(_fromUtf8(""))
        self.label91_3.setObjectName(_fromUtf8("label91_3"))
        self.verticalLayout_2.addWidget(self.label91_3)
        self.label101_2 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label101_2.setFont(font)
        self.label101_2.setText(_fromUtf8(""))
        self.label101_2.setObjectName(_fromUtf8("label101_2"))
        self.verticalLayout_2.addWidget(self.label101_2)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 500, 91, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(260, 100, 501, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label94_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label94_2.setFont(font)
        self.label94_2.setText(_fromUtf8(""))
        self.label94_2.setObjectName(_fromUtf8("label94_2"))
        self.gridLayout_2.addWidget(self.label94_2, 9, 2, 1, 1)
        self.label106_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label106_2.setFont(font)
        self.label106_2.setText(_fromUtf8(""))
        self.label106_2.setObjectName(_fromUtf8("label106_2"))
        self.gridLayout_2.addWidget(self.label106_2, 10, 4, 1, 1)
        self.label85_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label85_2.setFont(font)
        self.label85_2.setText(_fromUtf8(""))
        self.label85_2.setObjectName(_fromUtf8("label85_2"))
        self.gridLayout_2.addWidget(self.label85_2, 8, 3, 1, 1)
        self.label12_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label12_2.setFont(font)
        self.label12_2.setText(_fromUtf8(""))
        self.label12_2.setObjectName(_fromUtf8("label12_2"))
        self.gridLayout_2.addWidget(self.label12_2, 1, 0, 1, 1)
        self.label33_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label33_2.setFont(font)
        self.label33_2.setText(_fromUtf8(""))
        self.label33_2.setObjectName(_fromUtf8("label33_2"))
        self.gridLayout_2.addWidget(self.label33_2, 3, 1, 1, 1)
        self.label22_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label22_2.setFont(font)
        self.label22_2.setText(_fromUtf8(""))
        self.label22_2.setObjectName(_fromUtf8("label22_2"))
        self.gridLayout_2.addWidget(self.label22_2, 2, 0, 1, 1)
        self.label44_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label44_2.setFont(font)
        self.label44_2.setText(_fromUtf8(""))
        self.label44_2.setObjectName(_fromUtf8("label44_2"))
        self.gridLayout_2.addWidget(self.label44_2, 4, 2, 1, 1)
        self.label13_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label13_2.setFont(font)
        self.label13_2.setText(_fromUtf8(""))
        self.label13_2.setObjectName(_fromUtf8("label13_2"))
        self.gridLayout_2.addWidget(self.label13_2, 1, 1, 1, 1)
        self.label42_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label42_2.setFont(font)
        self.label42_2.setText(_fromUtf8(""))
        self.label42_2.setObjectName(_fromUtf8("label42_2"))
        self.gridLayout_2.addWidget(self.label42_2, 4, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 0, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 0, 3, 1, 1)
        self.label32_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label32_2.setFont(font)
        self.label32_2.setText(_fromUtf8(""))
        self.label32_2.setObjectName(_fromUtf8("label32_2"))
        self.gridLayout_2.addWidget(self.label32_2, 3, 0, 1, 1)
        self.label75_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label75_2.setFont(font)
        self.label75_2.setText(_fromUtf8(""))
        self.label75_2.setObjectName(_fromUtf8("label75_2"))
        self.gridLayout_2.addWidget(self.label75_2, 7, 3, 1, 1)
        self.label93_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label93_2.setFont(font)
        self.label93_2.setText(_fromUtf8(""))
        self.label93_2.setObjectName(_fromUtf8("label93_2"))
        self.gridLayout_2.addWidget(self.label93_2, 9, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 0, 1, 1, 1)
        self.label23_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label23_2.setFont(font)
        self.label23_2.setText(_fromUtf8(""))
        self.label23_2.setObjectName(_fromUtf8("label23_2"))
        self.gridLayout_2.addWidget(self.label23_2, 2, 1, 1, 1)
        self.label72_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label72_2.setFont(font)
        self.label72_2.setText(_fromUtf8(""))
        self.label72_2.setObjectName(_fromUtf8("label72_2"))
        self.gridLayout_2.addWidget(self.label72_2, 7, 0, 1, 1)
        self.label96_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label96_2.setFont(font)
        self.label96_2.setText(_fromUtf8(""))
        self.label96_2.setObjectName(_fromUtf8("label96_2"))
        self.gridLayout_2.addWidget(self.label96_2, 9, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 0, 4, 1, 1)
        self.label74_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label74_2.setFont(font)
        self.label74_2.setText(_fromUtf8(""))
        self.label74_2.setObjectName(_fromUtf8("label74_2"))
        self.gridLayout_2.addWidget(self.label74_2, 7, 2, 1, 1)
        self.label84_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label84_2.setFont(font)
        self.label84_2.setText(_fromUtf8(""))
        self.label84_2.setObjectName(_fromUtf8("label84_2"))
        self.gridLayout_2.addWidget(self.label84_2, 8, 2, 1, 1)
        self.label52_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label52_2.setFont(font)
        self.label52_2.setText(_fromUtf8(""))
        self.label52_2.setObjectName(_fromUtf8("label52_2"))
        self.gridLayout_2.addWidget(self.label52_2, 5, 0, 1, 1)
        self.label102_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label102_2.setFont(font)
        self.label102_2.setText(_fromUtf8(""))
        self.label102_2.setObjectName(_fromUtf8("label102_2"))
        self.gridLayout_2.addWidget(self.label102_2, 10, 0, 1, 1)
        self.label92_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label92_2.setFont(font)
        self.label92_2.setText(_fromUtf8(""))
        self.label92_2.setObjectName(_fromUtf8("label92_2"))
        self.gridLayout_2.addWidget(self.label92_2, 9, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.label82_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label82_2.setFont(font)
        self.label82_2.setText(_fromUtf8(""))
        self.label82_2.setObjectName(_fromUtf8("label82_2"))
        self.gridLayout_2.addWidget(self.label82_2, 8, 0, 1, 1)
        self.label36_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label36_2.setFont(font)
        self.label36_2.setText(_fromUtf8(""))
        self.label36_2.setObjectName(_fromUtf8("label36_2"))
        self.gridLayout_2.addWidget(self.label36_2, 3, 4, 1, 1)
        self.label62_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label62_2.setFont(font)
        self.label62_2.setText(_fromUtf8(""))
        self.label62_2.setObjectName(_fromUtf8("label62_2"))
        self.gridLayout_2.addWidget(self.label62_2, 6, 0, 1, 1)
        self.label83_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label83_2.setFont(font)
        self.label83_2.setText(_fromUtf8(""))
        self.label83_2.setObjectName(_fromUtf8("label83_2"))
        self.gridLayout_2.addWidget(self.label83_2, 8, 1, 1, 1)
        self.label24_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label24_2.setFont(font)
        self.label24_2.setText(_fromUtf8(""))
        self.label24_2.setObjectName(_fromUtf8("label24_2"))
        self.gridLayout_2.addWidget(self.label24_2, 2, 2, 1, 1)
        self.label104_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label104_2.setFont(font)
        self.label104_2.setText(_fromUtf8(""))
        self.label104_2.setObjectName(_fromUtf8("label104_2"))
        self.gridLayout_2.addWidget(self.label104_2, 10, 2, 1, 1)
        self.label95_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label95_2.setFont(font)
        self.label95_2.setText(_fromUtf8(""))
        self.label95_2.setObjectName(_fromUtf8("label95_2"))
        self.gridLayout_2.addWidget(self.label95_2, 9, 3, 1, 1)
        self.label66_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label66_2.setFont(font)
        self.label66_2.setText(_fromUtf8(""))
        self.label66_2.setObjectName(_fromUtf8("label66_2"))
        self.gridLayout_2.addWidget(self.label66_2, 6, 4, 1, 1)
        self.label34_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label34_2.setFont(font)
        self.label34_2.setText(_fromUtf8(""))
        self.label34_2.setObjectName(_fromUtf8("label34_2"))
        self.gridLayout_2.addWidget(self.label34_2, 3, 2, 1, 1)
        self.label56_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label56_2.setFont(font)
        self.label56_2.setText(_fromUtf8(""))
        self.label56_2.setObjectName(_fromUtf8("label56_2"))
        self.gridLayout_2.addWidget(self.label56_2, 5, 4, 1, 1)
        self.label103_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label103_2.setFont(font)
        self.label103_2.setText(_fromUtf8(""))
        self.label103_2.setObjectName(_fromUtf8("label103_2"))
        self.gridLayout_2.addWidget(self.label103_2, 10, 1, 1, 1)
        self.label25_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label25_2.setFont(font)
        self.label25_2.setText(_fromUtf8(""))
        self.label25_2.setObjectName(_fromUtf8("label25_2"))
        self.gridLayout_2.addWidget(self.label25_2, 2, 3, 1, 1)
        self.label15_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label15_2.setFont(font)
        self.label15_2.setText(_fromUtf8(""))
        self.label15_2.setObjectName(_fromUtf8("label15_2"))
        self.gridLayout_2.addWidget(self.label15_2, 1, 3, 1, 1)
        self.label53_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label53_2.setFont(font)
        self.label53_2.setText(_fromUtf8(""))
        self.label53_2.setObjectName(_fromUtf8("label53_2"))
        self.gridLayout_2.addWidget(self.label53_2, 5, 1, 1, 1)
        self.label86_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label86_2.setFont(font)
        self.label86_2.setText(_fromUtf8(""))
        self.label86_2.setObjectName(_fromUtf8("label86_2"))
        self.gridLayout_2.addWidget(self.label86_2, 8, 4, 1, 1)
        self.label54_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label54_2.setFont(font)
        self.label54_2.setText(_fromUtf8(""))
        self.label54_2.setObjectName(_fromUtf8("label54_2"))
        self.gridLayout_2.addWidget(self.label54_2, 5, 2, 1, 1)
        self.label43_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label43_2.setFont(font)
        self.label43_2.setText(_fromUtf8(""))
        self.label43_2.setObjectName(_fromUtf8("label43_2"))
        self.gridLayout_2.addWidget(self.label43_2, 4, 1, 1, 1)
        self.label63_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label63_2.setFont(font)
        self.label63_2.setText(_fromUtf8(""))
        self.label63_2.setObjectName(_fromUtf8("label63_2"))
        self.gridLayout_2.addWidget(self.label63_2, 6, 1, 1, 1)
        self.label16_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label16_2.setFont(font)
        self.label16_2.setText(_fromUtf8(""))
        self.label16_2.setObjectName(_fromUtf8("label16_2"))
        self.gridLayout_2.addWidget(self.label16_2, 1, 4, 1, 1)
        self.label105_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label105_2.setFont(font)
        self.label105_2.setText(_fromUtf8(""))
        self.label105_2.setObjectName(_fromUtf8("label105_2"))
        self.gridLayout_2.addWidget(self.label105_2, 10, 3, 1, 1)
        self.label46_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label46_2.setFont(font)
        self.label46_2.setText(_fromUtf8(""))
        self.label46_2.setObjectName(_fromUtf8("label46_2"))
        self.gridLayout_2.addWidget(self.label46_2, 4, 4, 1, 1)
        self.label14_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label14_2.setFont(font)
        self.label14_2.setText(_fromUtf8(""))
        self.label14_2.setObjectName(_fromUtf8("label14_2"))
        self.gridLayout_2.addWidget(self.label14_2, 1, 2, 1, 1)
        self.label35_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label35_2.setFont(font)
        self.label35_2.setText(_fromUtf8(""))
        self.label35_2.setObjectName(_fromUtf8("label35_2"))
        self.gridLayout_2.addWidget(self.label35_2, 3, 3, 1, 1)
        self.label45_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label45_2.setFont(font)
        self.label45_2.setText(_fromUtf8(""))
        self.label45_2.setObjectName(_fromUtf8("label45_2"))
        self.gridLayout_2.addWidget(self.label45_2, 4, 3, 1, 1)
        self.label55_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label55_2.setFont(font)
        self.label55_2.setText(_fromUtf8(""))
        self.label55_2.setObjectName(_fromUtf8("label55_2"))
        self.gridLayout_2.addWidget(self.label55_2, 5, 3, 1, 1)
        self.label65_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label65_2.setFont(font)
        self.label65_2.setText(_fromUtf8(""))
        self.label65_2.setObjectName(_fromUtf8("label65_2"))
        self.gridLayout_2.addWidget(self.label65_2, 6, 3, 1, 1)
        self.label73_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label73_2.setFont(font)
        self.label73_2.setText(_fromUtf8(""))
        self.label73_2.setObjectName(_fromUtf8("label73_2"))
        self.gridLayout_2.addWidget(self.label73_2, 7, 1, 1, 1)
        self.label26_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label26_2.setFont(font)
        self.label26_2.setText(_fromUtf8(""))
        self.label26_2.setObjectName(_fromUtf8("label26_2"))
        self.gridLayout_2.addWidget(self.label26_2, 2, 4, 1, 1)
        self.label112_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label112_2.setText(_fromUtf8(""))
        self.label112_2.setObjectName(_fromUtf8("label112_2"))
        self.gridLayout_2.addWidget(self.label112_2, 11, 0, 1, 1)
        self.label113_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label113_2.setText(_fromUtf8(""))
        self.label113_2.setObjectName(_fromUtf8("label113_2"))
        self.gridLayout_2.addWidget(self.label113_2, 11, 1, 1, 1)
        self.label114_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label114_2.setText(_fromUtf8(""))
        self.label114_2.setObjectName(_fromUtf8("label114_2"))
        self.gridLayout_2.addWidget(self.label114_2, 11, 2, 1, 1)
        self.label115_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label115_2.setText(_fromUtf8(""))
        self.label115_2.setObjectName(_fromUtf8("label115_2"))
        self.gridLayout_2.addWidget(self.label115_2, 11, 3, 1, 1)
        self.label116_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label116_2.setText(_fromUtf8(""))
        self.label116_2.setObjectName(_fromUtf8("label116_2"))
        self.gridLayout_2.addWidget(self.label116_2, 11, 4, 1, 1)
        self.label64_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label64_2.setText(_fromUtf8(""))
        self.label64_2.setObjectName(_fromUtf8("label64_2"))
        self.gridLayout_2.addWidget(self.label64_2, 6, 2, 1, 1)
        self.label76_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label76_2.setFont(font)
        self.label76_2.setText(_fromUtf8(""))
        self.label76_2.setObjectName(_fromUtf8("label76_2"))
        self.gridLayout_2.addWidget(self.label76_2, 7, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 470, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 470, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        MainWindow009.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow009)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow009.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow009)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow009.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow009)
        QtCore.QMetaObject.connectSlotsByName(MainWindow009)

    def retranslateUi(self, MainWindow009):
        MainWindow009.setWindowTitle(_translate("MainWindow009", "CRICKET APP", None))
        self.label.setText(_translate("MainWindow009", "Batting   Stats", None))
        self.label_15.setText(_translate("MainWindow009", "Player", None))
        self.pushButton_2.setText(_translate("MainWindow009", "Close", None))
        self.label_36.setText(_translate("MainWindow009", "Six", None))
        self.label_37.setText(_translate("MainWindow009", "Four", None))
        self.label_38.setText(_translate("MainWindow009", "BALL", None))
        self.label_39.setText(_translate("MainWindow009", "Strike", None))
        self.label_28.setText(_translate("MainWindow009", "Run", None))
        self.label_4.setText(_translate("MainWindow009", "Score", None))

import pro
